palabras = [
    "HUMANIDAD",
    "HUMANO",
    "PERSONA",
    "GENTE",
    "HOMBRE",
    "MUJER",
    "BEBE",
    "NIÑO",
    "ADOLESCENTE",
    "ADULTO",
    "ANCIANO",
    "DON",
    "SEÑOR",
    "CABALLERO",
    "DAMA",
    "INDIVIDUO",
    "CUERPO",
    "CUERPO",
    "PIERNA",
    "PIE",
    "TALON",
    "ESPINILLA",
    "RODILLA",
    "MUSLO",
    "CABEZA",
    "CARA",
    "BOCA",
    "LABIO",
    "DIENTE",
    "OJO",
    "NARIZ",
    "BARBA",
    "BIGOTE",
    "CABELLO",
    "OREJA",
    "CEREBRO",
    "ESTOMAGO",
    "BRAZO",
    "CODO",
    "HOMBRO",
    "UÑA",
    "MANO",
    "MUÑECA",
    "PALMA",
    "DEDO",
    "TRASERO",
    "ABDOMEN",
    "HIGADO",
    "MUSCULO",
    "CUELLO",
    "CORAZON",
    "MENTE",
    "ALMA",
    "ESPIRITU",
    "PECHO",
    "CINTURA",
    "CADERA",
    "ESPALDA",
    "SANGRE",
    "CARNE",
    "PIEL",
    "HUESO",
    "RESFRIADO",
    "GRIPE",
    "DIARREA",
    "SALUD",
    "ENFERMEDAD",
    "FAMILIA",
    "FAMILIA",
    "AMIGO",
    "CONOCIDO",
    "COLEGA",
    "PAREJA",
    "ESPOSO",
    "MATRIMONIO",
    "AMOR",
    "PADRE",
    "MADRE",
    "HERMANO",
    "HIJO",
    "ABUELO",
    "BISABUELO",
    "NIETO",
    "BISNIETO",
    "PRIMO",
    "TIO",
    "SOBRINO",
    "VIDA",
    "CRIATURA",
    "ESPECIE",
    "SER",
    "VIDA",
    "NACIMIENTO",
    "REPRODUCCION",
    "MUERTE",
    "GEOGRAFIA",
    "NATURALEZA",
    "CAMPO",
    "BOSQUE",
    "SELVA",
    "DESIERTO",
    "COSTA",
    "PLAYA",
    "RIO",
    "LAGUNA",
    "MAR",
    "CERRO",
    "LUZ",
    "ENERGIA",
    "ANIMALES",
    "ANIMAL",
    "PERRO",
    "GATO",
    "VACA",
    "CERDO",
    "CABALLO",
    "OVEJA",
    "MONO",
    "RATON",
    "TIGRE",
    "CONEJO",
    "DRAGON",
    "CIERVO",
    "RANA",
    "LEON",
    "JIRAFA",
    "ELEFANTE",
    "PAJARO",
    "GALLINA",
    "GORRION",
    "CUERVO",
    "AGUILA",
    "HALCON",
    "PEZ",
    "CAMARON",
    "LANGOSTA",
    "SARDINA",
    "ATUN",
    "CALAMAR",
    "PULPO",
    "INSECTO",
    "BICHO",
    "MARIPOSA",
    "POLILLA",
    "SALTAMONTES",
    "ARAÑA",
    "MOSCA",
    "MOSQUITO",
    "CUCARACHA",
    "CARACOL",
    "BABOSA",
    "LOMBRIZ",
    "MARISCO",
    "MOLUSCO",
    "LAGARTO",
    "SERPIENTE",
    "COCODRILO",
    "PLANTAS",
    "ALIMENTO",
    "COMIDA",
    "BEBIDA",
    "VEGETAL",
    "PLANTA",
    "PASTO",
    "FLOR",
    "FRUTA",
    "SEMILLA",
    "ARBOL",
    "HOJA",
    "RAIZ",
    "TALLO",
    "HONGO",
    "CIRUELA",
    "PINO",
    "BAMBU",
    "NUEZ",
    "ALMENDRA",
    "CASTAÑA",
    "ARROZ",
    "AVENA",
    "CEBADA",
    "TRIGO",
    "VERDURA",
    "PATATAS",
    "JUDIAS",
    "RABANO",
    "ZANAHORIA",
    "MANZANA",
    "NARANJA",
    "PLATANO",
    "PERA",
    "CASTAÑO",
    "DURAZNO",
    "TOMATE",
    "SANDIA",
    "CARNE",
    "GASEOSA",
    "TIEMPO",
    "TIEMPO",
    "CALENDARIO",
    "EDAD",
    "EPOCA",
    "FECHA",
    "INSTANTE",
    "MOMENTO",
    "SEGUNDO",
    "MINUTO",
    "HORA",
    "DIA",
    "SEMANA",
    "ENTRE",
    "FIN",
    "MES",
    "AÑO",
    "DECADA",
    "SIGLO",
    "MILENIO",
    "AYER",
    "HOY",
    "MAÑANA",
    "AMANECER",
    "MEDIODIA",
    "TARDE",
    "ANOCHECER",
    "NOCHE",
    "LUNES",
    "MARTES",
    "MIERCOLES",
    "JUEVES",
    "VIERNES",
    "SABADO",
    "DOMINGO",
    "ESPACIO",
    "AMBIENTE",
    "ESPACIO",
    "ENTORNO",
    "AREA",
    "SUPERFICIE",
    "VOLUMEN",
    "REGION",
    "ZONA",
    "LADO",
    "MUNDO",
    "PLANETA",
    "SOL",
    "LUNA",
    "ESTRELLA",
    "GALAXIA",
    "UNIVERSO",
    "CLIMA",
    "DESPEJADO",
    "NUBLADO",
    "LLUVIA",
    "NIEVE",
    "VIENTO",
    "TRUENO",
    "RAYO",
    "TORMENTA",
    "CIELO",
    "ESTE",
    "OESTE",
    "SUR",
    "NORTE",
    "DERECHA",
    "IZQUIERDA",
    "DIAGONAL",
    "EXTERIOR",
    "INTERIOR",
    "MATERIALES",
    "CALOR",
    "AGUA",
    "HIELO",
    "VAPOR",
    "FUEGO",
    "GAS",
    "AIRE",
    "TIERRA",
    "PISO",
    "SUELO",
    "METAL",
    "HIERRO",
    "ORO",
    "PLATA",
    "PLOMO",
    "SAL",
    "BARRO",
    "MEDIDAS",
    "PESO",
    "METRO",
    "MILIMETRO",
    "LITRO",
    "GRAMO",
    "KILO",
    "CANTIDAD",
    "TOTAL",
    "MEDIDA",
    "SOCIEDAD",
    "SOCIEDAD",
    "COMUNIDAD",
    "REUNION",
    "ENCUENTRO",
    "ESTRUCTURA",
    "ADMINISTRACION",
    "ORGANIZACION",
    "ASOCIACION",
    "EMPRESA",
    "EQUIPO",
    "AUTORIDAD",
    "CARGO",
    "CAMPAÑA",
    "CLUB",
    "COMISION",
    "CONGRESO",
    "CONSEJO",
    "PARTIDO",
    "PAIS",
    "NACION",
    "GOBIERNO",
    "ESTADO",
    "PROVINCIA",
    "DEPARTAMENTO",
    "MUNICIPIO",
    "DEMOCRACIA",
    "DICTADURA",
    "POLITICA",
    "POLITICO",
    "PRESIDENTE"
    "MINISTRO",
    "DIRECTOR",
    "PARLAMENTARIO",
    "REPRESENTANTE",
    "GOBERNADOR",
    "POLICIA",
    "BOMBEROS",
    "CAPITAL",
    "CIUDAD",
    "POBLACION",
    "PUEBLO",
    "VILLA"
    "OBLIGACION"
    "LIBERTAD"
    "DERECHO"
    "PERMISO"
    "PROHIBICION"
    "CONSTITUCION"
    "LEY"
    "DECRETO"
    "NORMA"
    "ECONOMIA"
    "CONSUMO"
    "DEMANDA"
    "COMPAÑIA"
    "COMERCIO"
    "MERCADO"
    "SERVICIO"
    "PRODUCTO"
    "PRODUCCION"
    "TRANSACCION"
    "ALMACEN"
    "HOTEL"
    "FABRICA"
    "CUENTA"
    "BOLETO"
    "ENTRADA"
    "DINERO"
    "BILLETE"
    "VUELTO"
    "MAQUINA"
    "PRECIO"
    "VALOR"
    "OBJETOS"
    "HOGAR"
    "ESCRITORIO"
    "SILLA"
    "MESA"
    "CAMA"
    "DORMITORIO"
    "HABITACION"
    "CUARTO"
    "OFICINA"
    "PANEL"
    "PUERTA"
    "VENTANA"
    "ENTRADA"
    "HOGAR"
    "CASA"
    "APARTAMENTO"
    "EDIFICIO"
    "CONSTRUCCION"
    "ELEVADOR"
    "ESCALERA"
    "HERRAMIENTAS"
    "APARATO"
    "CAMARA"
    "AGUJA"
    "CLAVO"
    "HILO"
    "CUERDA"
    "BOLSILLO"
    "BOLSO"
    "BOLSA"
    "PARAGUAS"
    "PARASOL"
    "PANTALLA"
    "POMO"
    "LLAVE"
    "TRANCAR"
    "ARMA"
    "ESCULTURA"
    "LIBRO"
    "REVISTA"
    "CUADRO"
    "GRABADO"
    "ELECTRICIDAD"
    "CORRIENTE"
    "BASE"
    "PATA"
    "CONEXION"
    "ROPA"
    "ROPA"
    "PRENDA"
    "MANGA"
    "SOLAPA"
    "BOTON"
    "CREMALLERA"
    "CINTURON"
    "ZAPATO"
    "GAFAS"
    "PANTALON"
    "CAMISA"
    "CAMISETA"
    "ZAPATILLA"
    "CORDONES"
    "ABRIGO"
    "CHAQUETA"
    "CALCETINES"
    "BRAGAS"
    "CALZONCILLO"
    "SUJETADOR"
    "FALDA"
    "TRANSPORTES"
    "TRANSPORTE"
    "TRANSITO"
    "VEHICULO"
    "TREN"
    "SUBTERRANEO"
    "CAMINO"
    "VIA"
    "RUTA"
    "CALLE"
    "CARRETERA"
    "AUTOPISTA"
    "AVENIDA"
    "ESTACION"
    "AVION"
    "AEROPUERTO"
    "AUTOMOVIL"
    "BUS"
    "AMBULANCIA"
    "LENGUAJE"
    "NUMERO"
    "ALFABETO"
    "SIMBOLO"
    "PUNTO"
    "COMA"
    "RAIZ"
    "PAPEL"
    "CARTA"
    "COMUNICACION"
    "EXPRESION"
    "VOZ"
    "TEXTO"
    "PERIODISMO"
    "PERIODICO"
    "DICCIONARIO"
    "DOCUMENTO"
    "INFORME"
    "NOTICIA"
    "COMPUTADORA"
    "IDIOMA"
    "JAPONES"
    "INGLES"
    "CHINO"
    "ALEMAN"
    "ESPAÑOL"
    "FRANCES"
    "COLORES"
    "COLOR"
    "BLANCO"
    "NEGRO"
    "GRIS"
    "ROJO"
    "NARANJA"
    "AMARILLO"
    "VERDE"
    "CELESTE"
    "AZUL"
    "VIOLETA"
    "ROSA"
    "MARRON"
    "ACTIVIDADES"
    "CULTURA"
    "AUTOR"
    "ACTUACION"
    "ESPECTADOR"
    "ESPECTACULO"
    "ENTRETENIMIENTO"
    "ARTE"
    "CINE"
    "DIBUJO"
    "PINTURA"
    "MUSICA"
    "RELIGION"
    "DIOS"
    "ARTICULO"
    "EDUCACION"
    "ESCUELA"
    "INSTITUTO"
    "COLEGIO"
    "UNIVERSIDAD"
    "CLASE"
    "CURSO"
    "ESTUDIO"
    "FORMACION"
    "ANALISIS"
    "INVESTIGACION"
    "CONOCIMIENTO"
    "IDEA"
    "INFORMACION"
    "DATO"
    "FORMA"
    "MANERA"
    "MODO"
    "ESTILO"
    "FIGURA"
    "ELEMENTO"
    "USO"
    "CIENCIA"
    "ARITMETICA"
    "HISTORIA"
    "GEOGRAFIA"
    "EDUCACION"
    "DEPORTE"
    "CARRERA"
    "COMPETICION"
    "AYUDA"
    "FAVOR"
    "APOYO"
    "BUSQUEDA"
    "DUDA"
    "PREGUNTA"
    "RESPUESTA"
    "CUESTION"
    "SOLICITUD"
    "DECISION"
    "ELECCION"
    "CONSEJO"
    "SUGERENCIA"
    "ORDEN"
    "CONTROL"
    "SISTEMA"
    "TRABAJO"
    "EMPLEO"
    "PROFESION"
    "ESFUERZO"
    "NUMEROS"
    "CERO"
    "UNO"
    "DOS"
    "TRES"
    "CUATRO"
    "CINCO"
    "SEIS"
    "SIETE"
    "OCHO"
    "NUEVE"
    "DIEZ"
    "CIEN"
    "MIL"
    "MILLON"
    "LUGAR"
    "POSICION"
    "MOVIMIENTO"
    "VELOCIDAD"
    "ACELERACION"
    "DIRECCION"
    "TAMAÑO"
    "LARGO"
    "ALTO"
    "ANCHO"
    "MAYORIA"
    "MINORIA"
    "AUMENTO"
    "REDUCCION"
    "CRECIMIENTO"
    "FONDO"
    "FRENTE"
    "COSA"
    "ASPECTO"
    "CONTENIDO"
    "OBJETO"
    "PARTE"
    "SECTOR"
    "PALABRA"
    "NOMBRE"
    "CODIGO"
    "SECRETO"
    "FORMALIDAD"
    "PRESENTE"
    "PASADO"
    "FUTURO"
    "OCASION"
    "VEZ"
    "ACCION"
    "ACTIVIDAD"
    "ACTO"
    "PROGRAMA"
    "PROYECTO"
    "OBRA"
    "ACUERDO"
    "ACTITUD"
    "ATENCION"
    "CAPACIDAD"
    "CONCEPTO"
    "TEMA"
    "CONDICION"
    "CASO"
    "CONJUNTO"
    "GRUPO"
    "CREACION"
    "DESTRUCCION"
    "ORIGEN"
    "DESTINO"
    "OBJETIVO"
    "FUNCION"
    "RELACION"
    "REALIDAD"
    "SITUACION"
    "PROBLEMA"
    "INTENTO"
    "SOLUCION"
    "EFECTO"
    "RESULTADO"
    "LOGRO"
    "EXITO"
    "FRACASO"
    "CAUSA"
    "CONSECUENCIA"
    "BENEFICIO"
    "PERJUICIO"
    "CALIDAD"
    "TIPO"
    "ATAQUE"
    "DEFENSA"
    "PAZ"
    "CONFLICTO"
    "GUERRA"
    "CARACTER"
    "CARACTERISTICA"
    "CRISIS"
    "CAMBIO"
    "DESARROLLO"
    "PROGRESO"
    "AVANCE"
    "RETROCESO"
    "MEJORA"
    "DETERIORO"
    "COMIENZO"
    "TRANSCURSO"
    "FIN"
    "ETAPA"
    "FASE"
    "PASO"
    "SERIE"
    "SECUENCIA"
    "GRADO"
    "NIVEL"
    "PROCESO"
    "CORTE"
    "INTERRUPCION"
    "ESPERA"
    "DIFERENCIA"
    "SIMILITUD"
    "SENTIDO"
    "SENSACION"
    "VISTA"
    "OIDO"
    "TACTO"
    "OLFATO"
    "DOLOR"
    "CONCIENCIA"
    "PERCEPCION"
    "IMAGEN"
    "FUERZA"
    "POTENCIA"
    "PRESENCIA"
    "EXISTENCIA"
    "EXPERIENCIA"
    "POSIBILIDAD"
    "PROBABILIDAD"
    "VERDAD"
    "MENTIRA"
    "RAZON"
    "ACIERTO"
    "EQUIVOCACION"
    "NECESIDAD"
    "FALTA"
    "SIGNIFICADO"
    "CARACTER"
    "PERSONALIDAD"
    "PENSAMIENTO"
    "MEMORIA"
    "RECUERDO"
    "DESEO"
    "ALEGRIA"
    "TRISTEZA"
    "ENOJO"
    "PLACER"
    "EMPATIA"
    "INTERES"
    "ABURRIMIENTO"
    "CANSANCIO"
    "SORPRESA"
    "SUSTO"
    "SEGURIDAD"
    "CONFIANZA"
    "MIEDO"
    "EJEMPLO"
    "ADJETIVOS"
    "ADJETIVOS"
    "BUENO"
    "MALO"
    "SUPERIOR"
    "INFERIOR"
    "CENTRAL"
    "LATERAL"
    "FRONTAL"
    "TRASERO"
    "CIERTO"
    "REAL"
    "FALSO"
    "MAYOR"
    "MENOR"
    "IMPORTANTE"
    "NECESARIO"
    "ABSOLUTO"
    "RELATIVO"
    "CARO"
    "BARATO"
    "VIEJO"
    "JOVEN"
    "NUEVO"
    "CADA"
    "CUALQUIER"
    "DADO"
    "ACTUAL"
    "RECIENTE"
    "CAPAZ"
    "FACIL"
    "DIFICIL"
    "POSIBLE"
    "IMPOSIBLE"
    "PROBABLE"
    "IMPROBABLE"
    "ESTRICTO"
    "SERIO"
    "GENERAL"
    "PARTICULAR"
    "COMUN"
    "ESPECIAL"
    "USUAL"
    "UNICO"
    "RARO"
    "FUERTE"
    "DEBIL"
    "CORRECTO"
    "INCORRECTO"
    "CONTRARIO"
    "IGUAL"
    "DIFERENTE"
    "PARECIDO"
    "OTRO"
    "DIVERSO"
    "MANUAL"
    "AUTOMATICO"
    "UNIVERSAL"
    "MUNDIAL"
    "CONTINENTAL"
    "INTERNACIONAL"
    "NACIONAL"
    "REGIONAL"
    "LOCAL"
    "URBANO"
    "RURAL"
    "SOCIAL"
    "POLITICO"
    "CULTURAL"
    "ARTISTICO"
    "PROPIO"
    "AJENO"
    "PUBLICO"
    "PRIVADO"
    "ADJETIVOS"
    "ALTO"
    "BAJO"
    "GRAN"
    "GRANDE"
    "PEQUEÑO"
    "AMPLIO"
    "ANGOSTO"
    "COMPACTO"
    "DELGADO"
    "GRUESO"
    "CALIENTE"
    "FRIO"
    "LIGERO"
    "PESADO"
    "SUAVE"
    "FIRME"
    "FLEXIBLE"
    "DURO"
    "BLANDO"
    "CALUROSO"
    "FRIO"
    "FRESCO"
    "DELICIOSO"
    "HORRIBLE"
    "DULCE"
    "PICANTE"
    "SALADO"
    "AMARGO"
    "ANTERIOR"
    "POSTERIOR"
    "SIGUIENTE"
    "CERCANO"
    "LEJANO"
    "JUNTO"
    "UNIDO"
    "SEPARADO"
    "ALEJADO"
    "FELIZ"
    "TRISTE"
    "SOLO"
    "SOLITARIO"
    "CONTENTO"
    "TRANQUILO"
    "ENOJADO"
    "CALMO"
    "AGITADO"
    "ANSIOSO"
    "INTERESADO"
    "ABURRIDO"
    "ENCANTADO"
    "CANSADO"
    "SORPRENDIDO"
    "ASUSTADO"
    "DOLOROSO"
    "PICANTE"
    "APESTOSO"
    "PRIMER"
    "SEGUNDO"
    "TERCERO"
    "CUARTO"
    "QUINTO"
    "DECIMO"
    "CENTESIMO"
    "MILLONESIMO"
    "PENULTIMO"
    "ULTIMO"
    "MI"
    "TU"
    "SU"
    "NUESTRO"
    "VUESTRO"
    "VERBOS"
    "AUXILIARES"
    "SER"
    "ESTAR"
    "HABER"
    "EXISTENCIA"
    "APARECER"
    "DESAPARECER"
    "EXISTIR"
    "CAMBIAR"
    "CRECER"
    "VIVIR"
    "NACER"
    "MORIR"
    "MOVIMIENTO"
    "IR"
    "VENIR"
    "VOLVER"
    "PARTIR"
    "LLEGAR"
    "LLEVAR"
    "TRAER"
    "MOVER"
    "ARROJAR"
    "LANZAR"
    "COGER"
    "AGARRAR"
    "PONER"
    "QUITAR"
    "ALCANZAR"
    "ACERCAR"
    "ALEJAR"
    "LANZAR"
    "ARROJAR"
    "LANZAR"
    "COGER"
    "AGARRAR"
    "SUJETAR"
    "GOLPEAR"
    "PATEAR"
    "PONER"
    "QUITAR"
    "ALCANZAR"
    "ACERCAR"
    "ALEJAR"
    "RECOGER"
    "LEVANTAR"
    "TOMAR"
    "PEGAR"
    "SENSACIONES"
    "SENTIR"
    "VER"
    "OIR"
    "TOCAR"
    "OLER"
    "PERCIBIR"
    "EMOCIONES"
    "AMAR"
    "QUERER"
    "DESEAR"
    "ODIAR"
    "ENTRISTECERSE"
    "LLORAR"
    "REIR"
    "ENOJARSE"
    "ADMIRAR"
    "ALEGRARSE"
    "ENCANTARSE"
    "CONSOLAR"
    "INTERESARSE"
    "ABURRIRSE"
    "CANSARSE"
    "SORPRENDERSE"
    "ASUSTARSE"
    "ACTIVIDADES"
    "COMUNICARSE"
    "AFIRMAR"
    "NEGAR"
    "DECIR"
    "HABLAR"
    "CALLAR"
    "ESCRIBIR"
    "LEER"
    "ANALIZAR"
    "PENSAR"
    "CANTAR"
    "SEÑALAR"
    "APUÑALAR"
    "MORDER"
    "CLAVAR"
    "COMER"
    "BEBER"
    "ACORDAR"
    "AFECTAR"
    "GENERAR"
    "AÑADIR"
    "MEJORAR"
    "EMPEORAR"
    "SEGUIR"
    "AVANZAR"
    "RETROCEDER"
    "AYUDAR"
    "COMPLICAR"
    "REUNIRSE"
    "ENTREVISTAR"
    "ABRIR"
    "JUGAR"
    "TENER"
    "FALTAR"
    "DAR"
    "RECIBIR"
    "ROMPER"
    "DOBLAR"
    "CORTAR"
    "COMPRAR"
    "VENDER"
    "LLEVAR"
    "CAMBIAR"
    "INTERCAMBIAR"
    "SUSTITUIR"
    "CERRAR"
    "BUSCAR"
    "ENCONTRAR"
    "OBTENER"
    "CREAR"
    "CREER"
    "COMENZAR"
    "TERMINAR"
    "ABANDONAR"
    "DEJAR"
    "ENTRAR"
    "QUEDARSE"
    "SALIR"
    "ATENDER"
    "MEDIR"
    "PESAR"
    "CONSIDERAR"
    "COMPARAR"
    "EVALUAR"
    "DECIDIR"
    "CONSTRUIR"
    "DESTRUIR"
    "DEBER"
    "PODER"
    "CONOCER"
    "ENTENDER"
    "ATAR"
    "SABER"
    "TRABAJAR"
    "SEPARAR"
    "DESCANSAR"
    "DORMIR"
    "DESPERTAR"
    "ACEPTAR"
    "RECHAZAR"
    "DESCARTAR"
    "ACOMPAÑAR"
    "PEDIR"
    "PRETENDER"
    "PROPONER"
    "SUGERIR"
    "USAR"
    "HACER"
    "FABRICAR"
    "ARREGLAR"
    "EXPLICAR"
    "MOSTRAR"
    "TRATAR"
    "EVITAR"
    "PROBAR"
    "COMPROBAR"
    "VARIAR"
    "ESPERAR"
    "NECESITAR"
    "SIGNIFICAR"
    "PARECER"
    "DISTINGUIR"
]